FROM golang:1.23-alpine AS build

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . ./
RUN go build -o /bin/api ./cmd/api

FROM alpine:3.20

WORKDIR /app

COPY --from=build /bin/api /app/api

EXPOSE 8080

CMD ["/app/api"]
